AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/ClassLength:
  Enabled: false